name: Snapshot governance allocations

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 4" # 1am on Thursday (UTC)

jobs:
  snapshot:
    name: Snapshot governance allocations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Snapshot governance allocations
        run: yarn snapshot
        env:
          SUBGRAPH_URL: ${{ secrets.SUBGRAPH_URL }}

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        with:
          message: "chore: snapshot governance allocations"
          default_author: github_actions
          add: docs
          push: origin HEAD:main
